config/routes.rb
Rails.application.routes.draw do
  resources :megaliths
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/megalith.rb
class Megalith < ApplicationRecord
  has_one_attached :image
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/megaliths_controller.rb
class MegalithsController < ApplicationController
  before_action :set_megalith, only: %i[ show edit update destroy ]

  # GET /megaliths or /megaliths.json
  def index
    @megaliths = Megalith.all
  end

  # GET /megaliths/1 or /megaliths/1.json
  def show
  end

  # GET /megaliths/new
  def new
    @megalith = Megalith.new
  end

  # GET /megaliths/1/edit
  def edit
  end

  # POST /megaliths or /megaliths.json
  def create
    @megalith = Megalith.new(megalith_params)

    respond_to do |format|
      if @megalith.save
        format.html { redirect_to @megalith, notice: "Megalith was successfully created." }
        format.json { render :show, status: :created, location: @megalith }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @megalith.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /megaliths/1 or /megaliths/1.json
  def update
    respond_to do |format|
      if @megalith.update(megalith_params)
        format.html { redirect_to @megalith, notice: "Megalith was successfully updated." }
        format.json { render :show, status: :ok, location: @megalith }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @megalith.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /megaliths/1 or /megaliths/1.json
  def destroy
    @megalith.destroy
    respond_to do |format|
      format.html { redirect_to megaliths_url, notice: "Megalith was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_megalith
      @megalith = Megalith.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def megalith_params
      params.require(:megalith).permit(:Name, :City, :Address, :Category, :Description, :Latitude, :Longitude, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/megaliths_helper.rb
module MegalithsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Appforseed</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/megaliths/_form.html.erb
<%= form_with(model: megalith, local: true) do |form| %>
  <% if megalith.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(megalith.errors.count, "error") %> prohibited this megalith from being saved:</h2>

      <ul>
        <% megalith.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :Name %>
    <%= form.text_field :Name %>
  </div>

  <div class="field">
    <%= form.label :City %>
    <%= form.text_field :City %>
  </div>

  <div class="field">
    <%= form.label :Address %>
    <%= form.text_field :Address %>
  </div>

  <div class="field">
    <%= form.label :Category %>
    <%= form.text_field :Category %>
  </div>

  <div class="field">
    <%= form.label :Description %>
    <%= form.text_area :Description %>
  </div>

  <div class="field">
    <%= form.label :Latitude %>
    <%= form.number_field :Latitude %>
  </div>

  <div class="field">
    <%= form.label :Longitude %>
    <%= form.number_field :Longitude %>
  </div>

  <div class="field">
    <%= form.file_field :image %>
    <%= form.submit %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/megaliths/edit.html.erb
<h1>Editing Megalith</h1>

<%= render 'form', megalith: @megalith %>

<%= link_to 'Show', @megalith %> |
<%= link_to 'Back', megaliths_path %>

app/views/megaliths/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Megaliths</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>City</th>
      <th>Address</th>
      <th>Category</th>
      <th>Description</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @megaliths.each do |megalith| %>
      <tr>
        <td><%= megalith.Name %></td>
        <td><%= megalith.City %></td>
        <td><%= megalith.Address %></td>
        <td><%= megalith.Category %></td>
        <td><%= megalith.Description %></td>
        <td><%= megalith.Latitude %></td>
        <td><%= megalith.Longitude %></td>
        <td><%= image_tag megalith.image, style: "width: 30px" %></td>
        <td><%= link_to 'Show', megalith %></td>
        <td><%= link_to 'Edit', edit_megalith_path(megalith) %></td>
        <td><%= link_to 'Destroy', megalith, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Megalith', new_megalith_path %>

app/views/megaliths/new.html.erb
<h1>New Megalith</h1>

<%= render 'form', megalith: @megalith %>

<%= link_to 'Back', megaliths_path %>

app/views/megaliths/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @megalith.Name %>
</p>

<p>
  <strong>City:</strong>
  <%= @megalith.City %>
</p>

<p>
  <strong>Address:</strong>
  <%= @megalith.Address %>
</p>

<p>
  <strong>Category:</strong>
  <%= @megalith.Category %>
</p>

<p>
  <strong>Description:</strong>
  <%= @megalith.Description %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @megalith.Latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @megalith.Longitude %>
</p>

<p>
  <strong>Image:</strong>
  <%= image_tag @megalith.image.variant(resize: "200X200") %>
</p>


<%= link_to 'Edit', edit_megalith_path(@megalith) %> |
<%= link_to 'Back', megaliths_path %>